import "./globals.css";

import { Inter } from "next/font/google";
import { Layout } from "@/components/Layout";
import type { Metadata } from "next";
import clsx from "clsx";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={clsx(inter.className)}>
      <body className="overflow-x-hidden antialiased">
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
