name: CI
on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
jobs:
  all-cli-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '19.3.0'
      - run: npm run install
      - run: npm run test
      - run: npm run lint
      - run: npm run build
  # cypress-run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2-beta
  #       with:
  #         node-version: '19.3.0'
  #     - run: mv .env.example .env
  #     - uses: cypress-io/github-action@v2
  #       with:
  #         build: yarn build
  #         start: yarn serve
